#DataSource
spring:
  profiles: dev

  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  datasource:
    url: jdbc:mysql://49.233.74.211:3306/zj_exam?useUnicode=true&characterEncoding=utf-8
    username: cat
    password: cat123
    driverClass: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #    config-location: classpath:mybatis/mybatis-config.xml
    #    mapper-locations: classpath:mybatis/mapper/*.xml

#文件上传临时目录
#upload.file.absolute.path: /root/file/upload/
upload.file.absolute.path: D:/upload/


